[build]
publish = "."
# If you have a frontend build step, replace with your build command/output
# command = "npm run build" 
# publish = "dist"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["images/*"]

[template.environment]
SCP_TOKEN = "Your SportsCardsPro/PriceCharting API token"
